# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'

target 'Plugin' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for IonicRunner
  pod 'Capacitor'
  pod 'Movesense', :git => 'ssh://git@altssh.bitbucket.org:443/suunto/movesense-mobile-lib.git'
end

target 'PluginTests' do
  use_frameworks!

  pod 'Capacitor'
  pod 'Movesense', :git => 'ssh://git@altssh.bitbucket.org:443/suunto/movesense-mobile-lib.git'
end
